version: '3'
services:

  web:
    image: matthewfreilly/litbot
    environment:
      - DEBUG
 
  api:
    image: sample-express-app
    build: .
    networks:
      - backend
    ports:
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge